### PR TITLE
nwchem version 7.0 dockerfile; Lines 7, 54, and 55 need changes

### PR DESCRIPTION
**Pull request by Leticia-maria**
If you have a contribution policy, I can change the file accordingly. Lines 7, 54, and 55 need adjustments according to the default user used in the other dockerfiles.

### CODE REVIEW

**Review by edoapra — CHANGES_REQUESTED** [review]
@Leticia-maria thanks for the contribution.
* please put the Dockerfile in a new directory, following the existing pattern
* what is new from the Dockerfile compared to the existing ones?
* what is the size of the image? Including vim and htop will bloat the size of the image

**Comment by Leticia-maria** [comment]
> @Leticia-maria thanks for the contribution.
> 
>     * please put the Dockerfile in a new directory, following the existing pattern
>  I've put the Dockerfile in a directory
>     * what is new from the Dockerfile compared to the existing ones?
> The Dockerfile is for Ubuntu 20.04 (installing version 7 of NWChem)
>     * what is the size of the image? Including vim and htop will bloat the size of the image
>  I've removed vim and htop. The image has 72 MB. I can reduce if necessary.

**Comment by Leticia-maria** [comment]
Iive inserted the requested changes #6fc91ad075ab7105cca595ee0e1fcc90c0358f94

**Comment by edoapra** [comment]
> > I've removed vim and htop. The image has 72 MB. I can reduce if necessary.

No, the size is 2.59GB.  I am referring to the output of the command `docker images`.
Similar Dockerfile (e.g. https://github.com/nwchemgit/nwchem-dockerfiles/tree/master/nwchem-dev) are less than 0.7GB
I still don't understand what is new in this pull request that is not present in existing Dockerfiles of this repository

**Comment by Leticia-maria** [comment]
> > > I've removed vim and htop. The image has 72 MB. I can reduce if necessary.
> 
> No, the size is 2.59GB. I am referring to the output of the command `docker images`. Similar Dockerfile (e.g. https://github.com/nwchemgit/nwchem-dockerfiles/tree/master/nwchem-dev) are less than 0.7GB I still don't understand what is new in this pull request that is not present in existing Dockerfiles of this repository.

Now I see that the Dockerfiles has no differences

**Pull request closed without merging**
